# Урок 7

# Системы линейных уравнений. Часть 2

## Практическое задание

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$



__Решение а)__

Если матрица коэффициентов размера $n\times n$ и $det\neq0$ то можно использовать метода Крамера

$$\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$$
составим расширенную матрицу

$$\begin{pmatrix}
\left.\begin{matrix}
1 & -2 \\ 
3 & -4
\end{matrix}\right|
\begin{matrix}
1\\ 
7
\end{matrix}
\end{pmatrix}.$$
Посчитаем все определители

$$det A =
\begin{pmatrix}
1 & -2 \\ 
3 & -4
\end{pmatrix} = -4+6=2$$
$$det A_1 =
\begin{pmatrix}
1 & -2 \\ 
7 & -4
\end{pmatrix} = -4+14=10$$
$$det A_2 =
\begin{pmatrix}
1 & 1 \\ 
3 & 7
\end{pmatrix} = 7-3=4$$

Корни СЛАУ:
$$x_1=\frac{detA_1}{detA}=\frac{10}{2}=5\\
x_2=\frac{detA_2}{detA}=\frac{4}{2}=2$$

Проверка:
$$\begin{cases}
5-2\cdot2=1 \\
3\cdot5-4\cdot2=7
\end{cases}$$
решение верное: 

$x_1=5\\
x_2=2$


__Решение б)__

Если матрица коэффициентов размера $n\times n$ и $det\neq0$ то можно использовать метода Крамера

$\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$
составим расширенную матрицу

$$\begin{pmatrix}
\left.\begin{matrix}
2 & -1 & 5 \\ 
1 & 1 & -3\\
2 & 4 & -3
\end{matrix}\right|
\begin{matrix}
10\\ 
-2\\
1
\end{matrix}
\end{pmatrix}.$$
Посчитаем все определители

$$det A =
\begin{pmatrix}
2 & -1 & 5 \\ 
1 & 1 & -3\\
2 & 4 & -3
\end{pmatrix} = 2+20+6-10+24+1=43$$
$$det A_1 =
\begin{pmatrix}
10 & -1 & 5 \\ 
-2 & 1 & -3\\
1 & 4 & -3
\end{pmatrix} = 10-40+3-5+120-2=86$$
$$det A_2 =
\begin{pmatrix}
2 & 10 & 5 \\ 
1 & -2 & -3\\
2 & 1 & -3
\end{pmatrix} = -4+5-60+20+6-10=-43$$
$$det A_3 =
\begin{pmatrix}
2 & -1 & 10 \\ 
1 & 1 & -2\\
2 & 4 & -1
\end{pmatrix} = 2+40+4-20+16+1=43$$

Корни СЛАУ:
$$x_1=\frac{detA_1}{detA}=\frac{86}{43}=2\\
x_1=\frac{detA_2}{detA}=\frac{-43}{43}=-1\\
x_1=\frac{detA_3}{detA}=\frac{43}{43}=1$$

Проверка: 

$\begin{cases}
2\cdot 2-x_{2}\cdot (-1)+5\cdot 1=10 \\
2+(-1)-3\cdot 1=-2 \\
2\cdot 2+4\cdot (-1)+1=1
\end{cases}$ 

решение верное: 

$x_1=2\\
x_2=-1\\
x_3=1$



__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    


__Решение а)__

Если матрица коэффициентов размера $n\times n$ и $det(A_k)\neq0$, где $k=1,2,...n-1$, то можно использовать метод $LU$-разложения

$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

$det(A_1)=1\\
det(A_2)=5$ 

можно использовать метод
произведем следующие операции со строчками: $R_2-2\cdot R_1 \,и \,R_3-3\cdot R_1$

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

произведем следущую операцию со строчкой 3: $R_3-4\cdot R_2$ 

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$

Из коэффициентов получаем матрицу $L$:

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}\,\,
U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$

Проверим:

In [4]:
import numpy as np
L = np.array([[1,0,0],[2,1,0],[3,4,1]])
U = np.array([[1,2,4],[0,5,4],[0,0,2]])
L.dot(U)

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

__Решение б)__

Если матрица коэффициентов размера $n\times n$ и $det(A_k)\neq0$, где $k=1,2,...n-1$, то можно использовать метод $LU$-разложения

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

$det(A_1)=1\\
det(A_2)=3\\
det(A_3)=9$ 

можно использовать метод
произведем следующие операции со строчками: $R_2-2\cdot R_1 \,и \,R_3-3\cdot R_1\,и \,R_4-4\cdot R_1$

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$

произведем следующие операции со строчками: $R_3-5\cdot R_2 \,и \,R_4-6\cdot R_1$ 

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$$

произведем следущую операцию со строчкой 4: $R_4-7\cdot R_3$ 

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$

Из коэффициентов получаем матрицу $L$:

$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}\,\,
U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$

Проверим:

In [6]:
import numpy as np
L = np.array([[1,0,0,0],[2,1,0,0],[3,5,1,0],[4,6,7,1]])
U = np.array([[1,1,2,4],[0,3,4,1],[0,0,3,1],[0,0,0,4]])
A = L.dot(U)
A

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$



__Решение__

Если матрица коэффициентов размера $n\times n$ и $det(A_k)\neq0$, где $k=1,2,...n-1$, то можно использовать метод $LU$-разложения

Сформируем матрицу коэффициентов СЛАУ
$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$$

$det(A_1)=2\\
det(A_2)=3$ 

можно использовать метод
для удобства переставим местами 2 и 1 столбик

$$\begin{pmatrix}
1 & 2 & 3 \\ 
7 & 11 & 5 \\ 
8 & 9 & 4
\end{pmatrix}$$

произведем следующие операции со строчками: $R_2-7\cdot R_1 \,и \,R_3-8\cdot R_1$

$$\begin{pmatrix}
1 & 2 & 3 \\ 
0 & -3 & -16 \\ 
0 & -7 & -20
\end{pmatrix}$$

произведем следущую операцию со строчкой 3: $R_3-\frac{7}{3}\cdot R_2$ 

$$\begin{pmatrix}
1 & 2 & 3 \\ 
0 & -3 & -16 \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}$$

Из коэффициентов получаем матрицу $L$:

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
7 & 1 & 0 \\ 
8 & \frac{7}{3} & 1
\end{pmatrix}\,\,
U=\begin{pmatrix}
1 & 2 & 3 \\ 
0 & -3 & -16 \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}$$

Используя формулу $Ax=b=LUx=b=Ly=b$ найдем $y$: 

$$y_1=1\\
7y_1+y_2=-6 \Rightarrow y_2=-13\\
8y_1+\frac{7}{3}y_2+y_3=-5\Rightarrow y_3=-5+\frac{67}{3}=\frac{52}{3}$$

Теперь найдем корни СЛАУ, не забыв что меняли местами столбики в матрице коэффициентов:  

$$x_2+2x_1+3x_3=1\\
-3x_1-16x_3=-13\\
\frac{52}{3}x_3=\frac{52}{3} \Rightarrow x_3=1\\
x_1=\frac{-13+16}{3}=-1\\
x_2=1+2-3=0$$

корни СЛАУ: 
$x_1=-1\\
x_2 =0\\
x_3=1$

Проверяем: 

$$\begin{cases}
2\cdot(-1)+0+3=1 \\
11\cdot(-1)+0+5=-6 \\
9\cdot(-1)+0+4=-5
\end{cases}$$



__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$



__Решение__

Метод работает с квадратными симметричными матрицами $detA\neq0$ в этом случае корни СЛАУ можно вычислить по формуле $LL^{T}x=b=Ly$ 

Посчитаем коэффициенты матрицы $L$:  

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9},$$

$$l_{22}=\sqrt{a_{22}-u_{21}^{2}}=\sqrt{50 - 25}=\sqrt{25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left (-15-5\cdot(-5) \right)=2,$$

$$l_{33}=\sqrt{a_{33}-l_{13}^{2}-l_{23}^{2}}=\sqrt{38-5^2-2^2}=\sqrt{9}=3.$$

Составим матрицы $L$ и $L^{T}$: 

$$L=\begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}\,\,
L^{T}=\begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}$$

$Ly=b$ посчитаем $y$ 

$9y_1=531 \Rightarrow y_1=59\\
-5y_1+5y_2=-460 \Rightarrow y_2=\frac{-460+295}{5}=-33\\
5y_1+2y_2+3y_3=193 \Rightarrow y_3=\frac{193-295+66}{3}=-12$ 

Используя $Ly=b$ вычислим корни СЛАУ: 

$9x_1-5x_2+5x_3=59\\
5x2+2x_3=-33\\
3x_3=-12$ 

$x_3=-4\\
x_2=\frac{-33+8}{5}=-25\\
x_1=\frac{59-125+20}{9}=\frac{46}{9}$

Корни найдены, проверяем:  

$$\begin{cases}
    81\cdot \frac{46}{9}-45\cdot(-25)+45\cdot(-4)=531 \Rightarrow -414+1125-180=531\\
-45\cdot \frac{46}{9}+50\cdot(-25)-15\cdot(-4)=-460 \Rightarrow-5\cdot46-1250+60=-460\\
45\cdot \frac{46}{9}-15\cdot(-25)+38\cdot(-4)=193\Rightarrow 5\cdot46+375-152=193
\end{cases}$$


корни СЛАУ: 
$x_1=\frac{46}{9}\\
x_2 =-25\\
x_3=-4$



__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [40]:
# поиск корней методом Крамера
# зададим матрицу и вектор свободных коэффициентов
A = np.array([[ 1,  1,  2,  4],
              [ 2,  5,  8,  9],
              [ 3, 18, 29, 18],
              [ 4, 22, 53, 33]])
b= np.array([[2,5,5,3]])

# провека условий использование метода
if np.linalg.det(A)==0 and len(A)!=len(A[0]):
    print("метод Крамера не подходит")

det_A = np.linalg.det(A)
b_t=b.transpose()
b_t
x=[0 for i in range(len(A))]
for i in range(len(A)):
    K=np.copy(A)
    for j in range(len(A)):
        K[j][i]=b_t[j]
    x[i]=np.linalg.det(K)/det_A

print('Корни СЛАУ:')
for i in range(len(x)):
    print(f'х{i+1}={x[i]:0.2f}')



Корни СЛАУ:
х1=-23.69
х2=3.86
х3=-4.58
х4=7.75


In [52]:
# поиск корней методом Гаусса
# зададим матрицу и вектор свободных коэффициентов
A = np.array([[ 1,  1,  2,  4],
              [ 2,  5,  8,  9],
              [ 3, 18, 29, 18],
              [ 4, 22, 53, 33]])
b= np.array([[2,5,5,3]])
A_=np.append(A, b.transpose(), axis=1)
# проверка на количество решений
rank_A = np.linalg.matrix_rank(A)
rank_A_ = np.linalg.matrix_rank(A_)
N = len(A[0])
if rank_A!=rank_A_:
    print("Матрица коэф. несовместная, неопределенная. СЛАУ не имеет решения")
else:
    if rank_A!=N:
        print("Матрица коэф. совместная, неопределенная. СЛАУ имеет бесконечное количество решений")     
    else:
        print("Матрица коэф. совместная, определенная. СЛАУ имеет единственное решение")

AA=np.zeros((len(A_),len(A_[0])))  
print(AA)
for i in range(len(A_)):
    for j in range(len(A_[0])):
        AA[i][j]=A_[i][j]/A_[i][i]
print(AA)

Матрица коэф. совместная, определенная. СЛАУ имеет единственное решение
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1.         1.         2.         4.         2.        ]
 [0.4        1.         1.6        1.8        1.        ]
 [0.10344828 0.62068966 1.         0.62068966 0.17241379]
 [0.12121212 0.66666667 1.60606061 1.         0.09090909]]
