# Урок 3

# Матрицы и матричные операции. Часть 1

## Практическое задание

In [4]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    

Произведения матриц А и В не определено:

$$ \begin{pmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{pmatrix} \cdot \begin{pmatrix}
8 & 7 & 6 & 5\\
4 & 3 & 2 & 1
\end{pmatrix}= \begin{pmatrix}
1\cdot8+2\cdot4+3\cdot ??\\
\cdots
\end{pmatrix}$$

Произведения матриц В и А так же не определено

In [9]:
A = np.array([[1,2,3,4],[5,6,7,8]])
B = np.array([[8,7,6,5],[4,3,2,1]])
print(A.dot(B))

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [11]:
print(B.dot(A))

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;


Произведения матриц А и В определено как матрица С размера $2\times3$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 0
\end{pmatrix} \cdot \begin{pmatrix}
8 & 7 & 6\\
5 & 4 & 3\\
2 & 1 & 0\\
1 & 2 & 3\\
4 & 5 & 6
\end{pmatrix} = 
\begin{pmatrix}
1\cdot8+2\cdot5+3\cdot2+4\cdot1+5\cdot4 1\cdot7+2\cdot4+3\cdot1+4\cdot2+5\cdot5 1\cdot6+2\cdot3+3\cdot0+4\cdot3+5\cdot6\\
6\cdot8+7\cdot5+8\cdot2+9\cdot1+0\cdot4 6\cdot7+7\cdot4+8\cdot1+9\cdot2+0\cdot5 6\cdot6+7\cdot3+8\cdot0+9\cdot3+0\cdot6
\end{pmatrix} = 
\begin{pmatrix}
48 & 51 & 54\\
108 & 96 & 84 
\end{pmatrix}$$

In [10]:
A = np.array([[1,2,3,4,5],[6,7,8,9,0]])
B = np.array([[8,7,6],[5,4,3],[2,1,0],[1,2,3],[4,5,6]])
A.dot(B)

array([[ 48,  51,  54],
       [108,  96,  84]])

Произведения матриц В и А не определено:

$$\begin{pmatrix}
8 & 7 & 6\\
5 & 4 & 3\\
2 & 1 & 0\\
1 & 2 & 3\\
4 & 5 & 6
\end{pmatrix} \cdot \begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 0
\end{pmatrix} = 
\begin{pmatrix}
8\cdot1+7\cdot6+6\cdot??\\
\dots
\end{pmatrix}$$

In [12]:
B.dot(A)

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;


Произведения матриц А и В определено как матрица С размера $8\times8$:

$$\begin{pmatrix}
8 & 7 & 6\\
5 & 4 & 3\\
2 & 1 & 0\\
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9\\
0 & 1 & 2\\
3 & 4 & 5
\end{pmatrix} \cdot
\begin{pmatrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\
9 & 0 & 1 & 2 & 3 & 4 & 5 & 6\\
7 & 8 & 9 & 0 & 1 & 2 & 3 & 4
\end{pmatrix} = 
\begin{pmatrix}
8\cdot1+7\cdot9+6\cdot7 & 8\cdot2+7\cdot0+6\cdot8 & 8\cdot3+7\cdot1+6\cdot9 & 8\cdot4+7\cdot2+6\cdot0 8\cdot5+7\cdot3+6\cdot1 & 8\cdot6+7\cdot4+6\cdot2 & 8\cdot7+7\cdot5+6\cdot3 & 8\cdot8+7\cdot6+6\cdot4\\
8\cdot1+7\cdot9+6\cdot7 & 8\cdot2+7\cdot0+6\cdot8 & 8\cdot3+7\cdot1+6\cdot9 & 8\cdot4+7\cdot2+6\cdot0 8\cdot5+7\cdot3+6\cdot1 & 8\cdot6+7\cdot4+6\cdot2 & 8\cdot7+7\cdot5+6\cdot3 & 8\cdot8+7\cdot6+6\cdot4\\
8\cdot1+7\cdot9+6\cdot7 & 8\cdot2+7\cdot0+6\cdot8 & 8\cdot3+7\cdot1+6\cdot9 & 8\cdot4+7\cdot2+6\cdot0 8\cdot5+7\cdot3+6\cdot1 & 8\cdot6+7\cdot4+6\cdot2 & 8\cdot7+7\cdot5+6\cdot3 & 8\cdot8+7\cdot6+6\cdot4\\
8\cdot1+7\cdot9+6\cdot7 & 8\cdot2+7\cdot0+6\cdot8 & 8\cdot3+7\cdot1+6\cdot9 & 8\cdot4+7\cdot2+6\cdot0 8\cdot5+7\cdot3+6\cdot1 & 8\cdot6+7\cdot4+6\cdot2 & 8\cdot7+7\cdot5+6\cdot3 & 8\cdot8+7\cdot6+6\cdot4\\
8\cdot1+7\cdot9+6\cdot7 & 8\cdot2+7\cdot0+6\cdot8 & 8\cdot3+7\cdot1+6\cdot9 & 8\cdot4+7\cdot2+6\cdot0 8\cdot5+7\cdot3+6\cdot1 & 8\cdot6+7\cdot4+6\cdot2 & 8\cdot7+7\cdot5+6\cdot3 & 8\cdot8+7\cdot6+6\cdot4\\
8\cdot1+7\cdot9+6\cdot7 & 8\cdot2+7\cdot0+6\cdot8 & 8\cdot3+7\cdot1+6\cdot9 & 8\cdot4+7\cdot2+6\cdot0 8\cdot5+7\cdot3+6\cdot1 & 8\cdot6+7\cdot4+6\cdot2 & 8\cdot7+7\cdot5+6\cdot3 & 8\cdot8+7\cdot6+6\cdot4\\
8\cdot1+7\cdot9+6\cdot7 & 8\cdot2+7\cdot0+6\cdot8 & 8\cdot3+7\cdot1+6\cdot9 & 8\cdot4+7\cdot2+6\cdot0 8\cdot5+7\cdot3+6\cdot1 & 8\cdot6+7\cdot4+6\cdot2 & 8\cdot7+7\cdot5+6\cdot3 & 8\cdot8+7\cdot6+6\cdot4\\
8\cdot1+7\cdot9+6\cdot7 & 8\cdot2+7\cdot0+6\cdot8 & 8\cdot3+7\cdot1+6\cdot9 & 8\cdot4+7\cdot2+6\cdot0 8\cdot5+7\cdot3+6\cdot1 & 8\cdot6+7\cdot4+6\cdot2 & 8\cdot7+7\cdot5+6\cdot3 & 8\cdot8+7\cdot6+6\cdot4
\end{pmatrix} = 
\begin{pmatrix}
113 & 64 & 85 & 46 & 67 & 88 & 109 & 130\\
62 & 34 &  46 &  28 &  40 &  52 &  64 &  76\\
11 &  4 &   7 &   10 &  13 &  16 &   19 &   22\\
40 & 26 &  32 &   8 &  14 & 20 &   26 &  32\\
91 & 56 & 71 &  26 &  41 & 56 &   71 &   86\\
142 & 86 & 110 &  44 &  68 &  92 &  116 &  140\\
23 & 16 &  19 &   2 &  5 & 8&  11 &   14\\
74 & 46 & 58 &  20 &  32 & 44&  56 &  68
\end{pmatrix}$$

In [13]:
A = np.array([[8,7,6],[5,4,3],[2,1,0],[1,2,3],[4,5,6],[7,8,9],[0,1,2],[3,4,5]])
B = np.array([[1,2,3,4,5,6,7,8],[9,0,1,2,3,4,5,6],[7,8,9,0,1,2,3,4]])
A.dot(B)

array([[113,  64,  85,  46,  67,  88, 109, 130],
       [ 62,  34,  46,  28,  40,  52,  64,  76],
       [ 11,   4,   7,  10,  13,  16,  19,  22],
       [ 40,  26,  32,   8,  14,  20,  26,  32],
       [ 91,  56,  71,  26,  41,  56,  71,  86],
       [142,  86, 110,  44,  68,  92, 116, 140],
       [ 23,  16,  19,   2,   5,   8,  11,  14],
       [ 74,  46,  58,  20,  32,  44,  56,  68]])

Произведение матриц В и А определено как матрица С размера $3\times3$:
$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\
9 & 0 & 1 & 2 & 3 & 4 & 5 & 6\\
7 & 8 & 9 & 0 & 1 & 2 & 3 & 4
\end{pmatrix} \cdot
\begin{pmatrix}
8 & 7 & 6\\
5 & 4 & 3\\
2 & 1 & 0\\
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9\\
0 & 1 & 2\\
3 & 4 & 5
\end{pmatrix}= 
\begin{pmatrix}
1\cdot8+2\cdot5+3\cdot2+4\cdot1+5\cdot4+6\cdot7+7\cdot0+8\cdot3 & 1\cdot8+2\cdot5+3\cdot2+4\cdot1+5\cdot4+6\cdot7+7\cdot0+8\cdot3 & 1\cdot8+2\cdot5+3\cdot2+4\cdot1+5\cdot4+6\cdot7+7\cdot0+8\cdot3\\
1\cdot8+2\cdot5+3\cdot2+4\cdot1+5\cdot4+6\cdot7+7\cdot0+8\cdot3 & 1\cdot8+2\cdot5+3\cdot2+4\cdot1+5\cdot4+6\cdot7+7\cdot0+8\cdot3 & 1\cdot8+2\cdot5+3\cdot2+4\cdot1+5\cdot4+6\cdot7+7\cdot0+8\cdot3\\
1\cdot8+2\cdot5+3\cdot2+4\cdot1+5\cdot4+6\cdot7+7\cdot0+8\cdot3 & 1\cdot8+2\cdot5+3\cdot2+4\cdot1+5\cdot4+6\cdot7+7\cdot0+8\cdot3 & 1\cdot8+2\cdot5+3\cdot2+4\cdot1+5\cdot4+6\cdot7+7\cdot0+8\cdot3
\end{pmatrix} = 
\begin{pmatrix}
114 & 138 & 162\\
134 & 144 & 154\\
144 & 130 & 116
\end{pmatrix}$$


In [14]:
B.dot(A)

array([[114, 138, 162],
       [134, 144, 154],
       [144, 130, 116]])

    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


Произведения матриц А и В определено как матрица С размера $4\times4$:
$$\begin{pmatrix}
1 & 2 & 3 & 4\\
4 & 3 & 2 & 1\\
1 & 2 & 3 & 4\\
4 & 3 & 2 & 1
\end{pmatrix} \cdot
\begin{pmatrix}
4 & 3 & 2 & 1\\
1 & 2 & 3 & 4\\
4 & 3 & 2 & 1\\
1 & 2 & 3 & 4
\end{pmatrix} = 
\begin{pmatrix}
1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1\\
1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1\\
1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1\\
1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1
\end{pmatrix} = 
\begin{pmatrix}
22&24&26&28\\
28&26&24&22\\
22&24&26&28\\
28&26&24&22
\end{pmatrix}$$

In [15]:
A =np.array([[1,2,3,4],[4,3,2,1],[1,2,3,4],[4,3,2,1]])
B =np.array([[4,3,2,1],[1,2,3,4],[4,3,2,1],[1,2,3,4]])
A.dot(B)

array([[22, 24, 26, 28],
       [28, 26, 24, 22],
       [22, 24, 26, 28],
       [28, 26, 24, 22]])

Произведения матриц В и А определено как матрица С размера $4\times4$:
$$\begin{pmatrix}
4 & 3 & 2 & 1\\
4 & 3 & 2 & 1\\
1 & 2 & 3 & 4\\
4 & 3 & 2 & 1
\end{pmatrix} \cdot
\begin{pmatrix}
1 & 2 & 3 & 4\\
1 & 2 & 3 & 4\\
4 & 3 & 2 & 1\\
1 & 2 & 3 & 4
\end{pmatrix} = 
\begin{pmatrix}
1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1\\
1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1\\
1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1\\
1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1 & 1\cdot4+2\cdot1+3\cdot4+4\cdot1
\end{pmatrix} = 
\begin{pmatrix}
22&24&26&28\\
28&26&24&22\\
22&24&26&28\\
28&26&24&22
\end{pmatrix}$$

In [16]:
B.dot(A)

array([[22, 24, 26, 28],
       [28, 26, 24, 22],
       [22, 24, 26, 28],
       [28, 26, 24, 22]])

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1+4&-2-1\\
3+0&0+5
\end{pmatrix} = 
\begin{pmatrix}
5&-3\\
3&5
\end{pmatrix}
$$

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1\cdot4+(-2)\cdot0 & 1\cdot(-1)+(-2)\cdot5\\
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5
\end{pmatrix} = 
\begin{pmatrix}
4&-11\\
12&-3
\end{pmatrix}
$$

In [19]:
A=np.array([[1,-2],[3,0]])
B=np.array([[4,-1],[0,5]])
print(A+B)
print(A.dot(B))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    


$$3A-2B+4C=3\cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}-2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+4\cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3\cdot1-2\cdot0+4\cdot2 & 3\cdot7-2\cdot5+4\cdot(-4)\\
3\cdot3-2\cdot2+4\cdot1 & 3\cdot(-6)-2\cdot(-1)+4\cdot1
\end{pmatrix} = 
\begin{pmatrix}
11&-5\\
9&-12
\end{pmatrix}
$$

In [20]:
A = np.array([[1,7],[3,-6]])
B =np.array([[0,5],[2,-1]])
C=np.array([[2,-4],[1,1]])
print(3*A-2*B+4*C)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.



$$A^{T}=\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}$$

$$A\cdot A^{T} =
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot
\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix} = 
\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\
5\cdot4-2\cdot1 & 5\cdot5-2\cdot(-2) & 5\cdot2-2\cdot3\\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}
$$

$$A^{T}\cdot A =
\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix} \cdot
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = 
\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\
1\cdot4-2\cdot5+3\cdot2 & 1\cdot1-2\cdot(-2)+3\cdot3\\
\end{pmatrix} = 
\begin{pmatrix}
45 & 0\\
0 & 14
\end{pmatrix}
$$

In [23]:
A = np.array([[4,1],[5,-2],[2,3]])
print(A.dot(A.T))
print((A.T).dot(A))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

Правило перемножения матриц можно сформулировать словесно следующим образом: _элемент $c_{ij}$, стоящий на пересечении $i$-й строки и $j$-го столбца матрицы $C=A\cdot B$, равен сумме попарных произведений соответствующих элементов $i$-й строки матрицы $A$ и $j$-го столбца матрицы $B$._
Следует заметить, что матрицу $A$ можно умножить не на всякую матрицу $B$: __необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.__

In [214]:
A = [[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]]
B = [[4,5,6],[4,5,6],[4,5,6]]
# определяем размерность матриц
m,n = len(A),len(A[0])
k,s = len(B),len(B[0])
# print(m,n,k,s)

# проверка возможности умножения
if n==k:
    product_AB(A,B,m,n,k,s)
else:
    print("произведение не определено")
    


def product_AB(A,B,m,n,k,s):
    # создаем столбцы по второй матрице
    B_columns = []
    for i in range(s):
        column =[]
        for j in range(k):
            column.append(B[j][i])
        B_columns.append(column)
    # print(B_columns)

    # создаем матрицу произведения
    C=[[0]*s for i in range(m)]
    # for row in C: 
    #     print(row)
    # цикл умножения
    # цикл по количеству столбцов 
    for i in range(s):
        # цикл по количеству строк 
        for j in range(m):
            C_ij=0
            # цикл по количеству значений в строке/столбце
            for h in range(k):
                #print(B_columns[i][h], A[j][h])
                C_ij=C_ij+B_columns[i][h]* A[j][h]
            #print(f'C_ij={B_columns[i][h]}*{A[j][h]}={C_ij}, i={j} j={i}')
            C[j][i] = C_ij

    print('A')
    for row in A: 
        print(row)
    print('*\nB')
    for row in B: 
        print(row)
    print('=\nC')
    for row in C: 
        print(row)

A
[1, 1, 1]
[2, 2, 2]
[3, 3, 3]
[4, 4, 4]
[5, 5, 5]
*
B
[4, 5, 6]
[4, 5, 6]
[4, 5, 6]
=
C
[12, 15, 18]
[24, 30, 36]
[36, 45, 54]
[48, 60, 72]
[60, 75, 90]


In [215]:
A = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])
B = np.array([[4,5,6],[4,5,6],[4,5,6]])
A.dot(B)

array([[12, 15, 18],
       [24, 30, 36],
       [36, 45, 54],
       [48, 60, 72],
       [60, 75, 90]])