# Урок 5

# Линейные преобразования

## Практическое задание

In [8]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$



Собственный вектор это не нулевой вектор, который остается коллинеарен прообразу после воздействия оператора меняет только размеры и направление(?- он же может поменять направление, верно?) 
тоесть всегда есть векторы на которых данное линейное преобразование только меняет его размер? ого

$$\textbf{A}x=\lambda x.$$



Hайдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)-2\cdot(-6)=0,$$

$$\lambda^2 -5\lambda+6=0$$

$$\lambda_1=\frac{5+\sqrt{5^2-4\cdot6}}{2}=\frac{5+1}{2}=3$$
$$\lambda_2=\frac{5+\sqrt{5^2-4\cdot6}}{2}=\frac{5-1}{2}=2$$

Вычисляем собственный вектор для $\lambda_1=3$
$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix} = 
\begin{pmatrix}
3x_1\\ 
3x_2
\end{pmatrix}$$

$$\Rightarrow
\begin{cases}
-1x_1-6x_2-3x_1=0\\ 
2x_1+6x_2-3x_2=0
\end{cases}
\Rightarrow
\begin{cases}
-2x_1-3x_2=0\\ 
2x_1+3x_2=0
\end{cases}\Rightarrow
\begin{cases}
x_1=-\frac{3}{2}x_2\\ 
-3x_2+3x_2=0
\end{cases}
\Rightarrow
\begin{cases}
x_1=-\frac{3}{2}x_2\\ 
x_2=x_2
\end{cases}$$
Пусть $x_2=1$, тогда собственный вектор $x(-\frac{3}{2},1)$

Вычисляем собственный вектор для $\lambda_2=2$
$$det(\textbf{A}-\lambda\textbf{I})=\begin{pmatrix}
-1-2 & -6\\ 
2 & 6-2
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix} = 
0$$

$$\Rightarrow
\begin{cases}
-3x_1-6x_2=0\\ 
2x_1+4x_2=0
\end{cases}
\Rightarrow
\begin{cases}
-x_1-2x_2=0\\ 
x_1+2x_2=0
\end{cases}\Rightarrow
\begin{cases}
x_1=-2x_2\\ 
-2x_2+2x_2=0
\end{cases}
\Rightarrow
\begin{cases}
x_1=-2x_2\\ 
x_2=x_2
\end{cases}$$
Пусть $x_2=1$, тогда собственный вектор $x(-2,1)$

In [9]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.



Собственный вектор это любой не нулевой вектор, который коллинеарен самому себе до преобразований. Любой вектор будет коллинеарен своему прообразу если его умножать на 1 или -1

Найдем собственные значения:
$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$
$$(-1-\lambda)(-1-\lambda)-0=0$$
$$1+2\lambda+\lambda^2=0$$
$$D=2^2-4=0$$
$$\lambda=\frac{-2}{2}=-1$$

Найдем собственный вектор:
$$\Rightarrow
\begin{cases}
-1x_1+1x_1=0\\ 
-1x_2+1x_2=0
\end{cases}
\Rightarrow
\begin{cases}
x_1=x_1\\ 
x_2=x_2
\end{cases}$$
Любой вектор может быть собственным вектором

In [10]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



Если $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

$$\Rightarrow
\begin{cases}
1+1=\lambda\\ 
-1+3=\lambda
\end{cases}
\Rightarrow
\begin{cases}
2=\lambda\\ 
2=\lambda
\end{cases}$$
$\lambda=2$ это значит что вектор $x(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$.

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

Если $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}.
$$

$$\Rightarrow
\begin{cases}
-9=3\lambda\\ 
9=-3\lambda\\
-12=-4\lambda\\
\end{cases}
\Rightarrow
\begin{cases}
-3=\lambda\\ 
-3=\lambda\\
-3=\lambda\\
\end{cases}$$
$\lambda=-3$ это значит что вектор $x(3,-3,-4)$ является собственным вектором линейного оператора, заданного матрицей $A$.